import type { Config } from "tailwindcss";

// Design tokens mapped to a L'Oreal-inspired black, charcoal, white, gray, and gold palette.
export default {
  content: ["./app/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#2A2A2A",
        "inverse-surface": "#F4F4F4",
        background: "#111111",
        "surface-container-high": "#2A2A2A",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#F4F4F4",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#1C1C1C",
        "surface-container-lowest": "#161616",
        "error-container": "#3A1414",
        "on-tertiary-fixed-variant": "#F4F4F4",
        "inverse-primary": "#D8C28A",
        "on-surface": "#FFFFFF",
        outline: "#8A8A8A",
        "on-primary-container": "#000000",
        "surface-dim": "#0D0D0D",
        "primary-fixed": "#D8C28A",
        secondary: "#D8C28A",
        "on-tertiary-fixed": "#F4F4F4",
        primary: "#C8A45D",
        tertiary: "#FFFFFF",
        "secondary-fixed-dim": "#B8B8B8",
        "inverse-on-surface": "#1C1C1C",
        "on-error-container": "#ffdad6",
        "on-background": "#FFFFFF",
        "primary-fixed-dim": "#C8A45D",
        "on-surface-variant": "#B8B8B8",
        "on-primary-fixed-variant": "#000000",
        "surface-bright": "#242424",
        "surface-container": "#242424",
        "secondary-container": "#242424",
        "surface-variant": "#333333",
        "tertiary-fixed-dim": "#C8A45D",
        "surface-tint": "#C8A45D",
        "surface-container-highest": "#3A3A3A",
        error: "#ffb4ab",
        "secondary-fixed": "#333333",
        "on-primary-fixed": "#000000",
        "tertiary-container": "#2A2A2A",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#F4F4F4",
        surface: "#181818",
        "outline-variant": "#3A3A3A",
        // 상태 시맨틱 컬러 — 다크 배경 위에서 눈이 편한 저채도 톤 (승인/대기/위험)
        success: "#6FBF9B",
        warning: "#E5B567",
        danger: "#E08F8F",
        "on-tertiary-container": "#F4F4F4",
        "on-secondary-container": "#F4F4F4",
        "primary-container": "#D8C28A",
        "on-primary": "#000000",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "card-gap": "16px",
        "stack-sm": "8px",
        "table-cell-px": "12px",
        "container-padding": "24px",
        "table-cell-py": "10px",
      },
      fontFamily: {
        "headline-sm": ["Pretendard Variable", "Pretendard", "sans-serif"],
        "metric-lg": ["Pretendard Variable", "Pretendard", "sans-serif"],
        "label-caps": ["Pretendard Variable", "Pretendard", "sans-serif"],
        "body-sm": ["Pretendard Variable", "Pretendard", "sans-serif"],
        "metric-md": ["Pretendard Variable", "Pretendard", "sans-serif"],
        "body-md": ["Pretendard Variable", "Pretendard", "sans-serif"],
        "label-muted": ["Pretendard Variable", "Pretendard", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "metric-lg": ["36px", { lineHeight: "40px", letterSpacing: "0", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "metric-md": ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-muted": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
