import type { Config } from "tailwindcss";

// Design tokens extracted verbatim from the Google Stitch "Celine Intelligence" project.
export default {
  content: ["./app/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdbcc",
        "inverse-surface": "#2f3038",
        background: "#fbf8ff",
        "surface-container-high": "#e8e7f1",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f4f2fd",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#7b2f00",
        "inverse-primary": "#c3c0ff",
        "on-surface": "#1a1b22",
        outline: "#777587",
        "on-primary-container": "#dad7ff",
        "surface-dim": "#dad9e3",
        "primary-fixed": "#e2dfff",
        secondary: "#565e74",
        "on-tertiary-fixed": "#351000",
        primary: "#3525cd",
        tertiary: "#7e3000",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#f1effa",
        "on-error-container": "#93000a",
        "on-background": "#1a1b22",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface-variant": "#464555",
        "on-primary-fixed-variant": "#3323cc",
        "surface-bright": "#fbf8ff",
        "surface-container": "#eeedf7",
        "secondary-container": "#dae2fd",
        "surface-variant": "#e3e1ec",
        "tertiary-fixed-dim": "#ffb695",
        "surface-tint": "#4d44e3",
        "surface-container-highest": "#e3e1ec",
        error: "#ba1a1a",
        "secondary-fixed": "#dae2fd",
        "on-primary-fixed": "#0f0069",
        "tertiary-container": "#a44100",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        surface: "#fbf8ff",
        "outline-variant": "#c7c4d8",
        "on-tertiary-container": "#ffd2be",
        "on-secondary-container": "#5c647a",
        "primary-container": "#4f46e5",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "card-gap": "16px",
        "stack-sm": "8px",
        "table-cell-px": "12px",
        "container-padding": "24px",
        "table-cell-py": "10px",
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "metric-lg": ["Inter"],
        "label-caps": ["Inter"],
        "body-sm": ["Inter"],
        "metric-md": ["Inter"],
        "body-md": ["Inter"],
        "label-muted": ["Inter"],
      },
      fontSize: {
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "metric-lg": ["36px", { lineHeight: "40px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "metric-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-muted": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
